#define	E_SUCCESS	0
#define	DRVBLT_VERSION_NUM	1

#ifndef	_W55FA92_BLT_REG_H_
#define _W55FA92_BLT_REG_H_

#define	E_SUCCESS	0
#define	DRVBLT_VERSION_NUM	1


#define	ELEMENTA REG_ELEMENTA
#define	ELEMENTB REG_ELEMENTB
#define	ELEMENTC REG_ELEMENTC
#define	ELEMENTD REG_ELEMENTD
#define	SFMT	 REG_SFMT
#define	DFMT	 REG_DFMT
#define	BLTINTCR	REG_BLTINTCR
#define	MLTB		REG_MLTB
#define	MLTG		REG_MLTG
#define	MLTR		REG_MLTR
#define	MLTA		REG_MLTA

#define	SADDR		REG_SADDR
#define	SSTRIDE		REG_SSTRIDE
#define	OFFSETSX	REG_OFFSETSX
#define	OFFSETSY	REG_OFFSETSY
#define	SWIDTH		REG_SWIDTH
#define	SHEIGHT		REG_SHEIGHT
#define	DADDR		REG_DADDR
#define	DSTRIDE		REG_DSTRIDE
#define	DWIDTH		REG_DWIDTH
#define	DHEIGHT		REG_DHEIGHT
#define FILLARGB	REG_FILLARGB
#define SET2DA		REG_SET2DA
#define	PALETTE	    REG_PALETTE
#define TR_RGB565	0xFFFF
#define	TRCOLOR_R	REG_TRCOLOR

#endif